version: "3.9"

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: discord-bot-kafka
    hostname: kafka
    environment:
      # 단일 브로커 + KRaft(컨트롤러+브로커 합쳐진 모드) 설정
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      # Kraft 클러스터를 식별 ID
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "9092:9092"
    networks:
      - botnet

  db:
    image: postgres:15
    container_name: discord-bot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discord_bot
      TZ: Asia/Seoul
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    # WSL(Windows): /srv/psql/15에 데이터 저장
    # Mac/Linux: ./postgres-data에 데이터 저장
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d discord_bot"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - botnet
    
  discord-bot:
    build: .
    image: discord-bot-image:${APP_ENV}
    restart: always
    container_name: discord-bot-app-${APP_ENV}
    environment:
      TZ: Asia/Seoul
      PYTHON_RUN_ENV: ${APP_ENV}
    volumes:
      - ./assets:/app/assets
      - ./data:/app/data
      - ./db:/app/db
      - ./env:/app/env
      - ./exceptions:/app/exceptions
      - ./kafka:/app/kafka
      - ./service:/app/service
      - ./bot_helper.py:/app/bot_helper.py
      - ./bot_logger.py:/app/bot_logger.py
      - ./config.py:/app/config.py
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - botnet

volumes:
  pgdata:

networks:
  botnet:
    driver: bridge